# Generated by Django 4.2.1 on 2023-05-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Write About Your Task..', max_length=300),
        ),
    ]
